In [4]:
# THis is pytorch tutorial.
from __future__ import print_function
import torch

# Construct a 5x3 matrix, uninitialized:
x = torch.empty(5, 3)
print(x)

tensor([[4.7984e+30, 6.2121e+22, 1.8370e+25],
        [1.4603e-19, 2.7517e+12, 7.5338e+28],
        [3.0313e+32, 6.3828e+28, 1.4603e-19],
        [1.0899e+27, 6.8943e+34, 1.1835e+22],
        [7.0976e+22, 1.8515e+28, 4.1988e+07]])


In [5]:
# Construct a matrix filled zeros and of dtype long:

x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
# Construct a tensor directly from data:
x = torch.tensor([5.5, 3])
print(x)


tensor([5.5000, 3.0000])


In [8]:
# or create a tensor based on an existing tensor.
# hese methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5782,  1.3569,  0.7788],
        [-0.4683, -0.9770, -0.5970],
        [-0.2814, -0.1413, -1.1366],
        [ 0.7811, -0.4018,  0.2002],
        [ 0.9938,  0.7632,  0.3693]])
